# Generated by Django 5.2.1 on 2025-05-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatbotAi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterAbonnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=10)),
                ('contenue', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyé', 'Envoyé')], default='brouillon', max_length=30)),
                ('date_envoie', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
