# Generated by Django 5.2.1 on 2025-05-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatbotAi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettermessage',
            name='objet',
            field=models.CharField(max_length=100),
        ),
    ]
