# Generated by Django 5.2.1 on 2025-05-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatbotAi', '0002_alter_newslettermessage_objet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettermessage',
            old_name='date_creation',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='newslettermessage',
            name='is_sent',
        ),
        migrations.AlterField(
            model_name='newslettermessage',
            name='objet',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newslettermessage',
            name='statut',
            field=models.CharField(default='brouillon', max_length=50),
        ),
    ]
