# Generated by Django 5.2.1 on 2025-05-30 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatbotAi', '0003_rename_date_creation_newslettermessage_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='ressources/')),
                ('type', models.CharField(choices=[('guide', 'Guide Pratique'), ('fiche', 'Fiche'), ('podcast', 'Podcast'), ('video', 'Vidéo')], default='guide', max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ChatbotAi.ressource')),
            ],
            bases=('ChatbotAi.ressource',),
        ),
        migrations.CreateModel(
            name='GuidePratique',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ChatbotAi.ressource')),
            ],
            bases=('ChatbotAi.ressource',),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ChatbotAi.ressource')),
                ('lien', models.URLField(blank=True, null=True)),
            ],
            bases=('ChatbotAi.ressource',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ChatbotAi.ressource')),
                ('lien', models.URLField(blank=True, null=True)),
            ],
            bases=('ChatbotAi.ressource',),
        ),
    ]
