# Generated by Django 5.2.1 on 2025-05-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatbotAi', '0004_ressource_fiche_guidepratique_podcast_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='lien',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lien',
        ),
        migrations.AddField(
            model_name='ressource',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
    ]
