# Generated by Django 5.2.1 on 2025-05-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatbotAi', '0005_remove_podcast_lien_remove_video_lien_ressource_lien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='type',
            field=models.CharField(choices=[('guide', 'Guide Pratique'), ('fiche', 'Vidéo Explicative'), ('podcast', 'Podcast Juridique'), ('video', 'Fiche Thématique')], default='guide', max_length=50),
        ),
    ]
