# Generated by Django 5.2.1 on 2025-06-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatbotAi', '0006_alter_ressource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='type',
            field=models.CharField(choices=[('guide', 'Guide Pratique'), ('fiche', 'Vidéo Explicative'), ('podcast', 'Podcast Juridique'), ('video', 'Fiche Thématique')], max_length=50),
        ),
    ]
